from .users import user_bp 
from .posts import post_bp 
from .tests import test_bp
from .core import core_bp
from .admin import admin_bp
from .api import api_bp
from .auth import auth_bp
from .presentation import presentation_bp
from .ai import ai_bp
from .stripe import stripe_bp